//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18051
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCon.Client.Base.ServerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credentials", Namespace="http://schemas.datacontract.org/2004/07/ComCon.Shared.Classes")]
    [System.SerializableAttribute()]
    public partial class Credentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ComCon.Shared.Classes")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVisible {
            get {
                return this.IsVisibleField;
            }
            set {
                if ((this.IsVisibleField.Equals(value) != true)) {
                    this.IsVisibleField = value;
                    this.RaisePropertyChanged("IsVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastOnline {
            get {
                return this.LastOnlineField;
            }
            set {
                if ((this.LastOnlineField.Equals(value) != true)) {
                    this.LastOnlineField = value;
                    this.RaisePropertyChanged("LastOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://schemas.datacontract.org/2004/07/ComCon.Shared.Classes")]
    [System.SerializableAttribute()]
    public partial class ChatMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Windows.Media.Color ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ComCon.Client.Base.ServerService.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Windows.Media.Color Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ComCon.Client.Base.ServerService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerService.IMainServerFunctions")]
    public interface IMainServerFunctions {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainServerFunctions/Authenticate", ReplyAction="http://tempuri.org/IMainServerFunctions/AuthenticateResponse")]
        ComCon.Client.Base.ServerService.User Authenticate(ComCon.Client.Base.ServerService.Credentials pCredentials);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMainServerFunctions/Authenticate", ReplyAction="http://tempuri.org/IMainServerFunctions/AuthenticateResponse")]
        System.IAsyncResult BeginAuthenticate(ComCon.Client.Base.ServerService.Credentials pCredentials, System.AsyncCallback callback, object asyncState);
        
        ComCon.Client.Base.ServerService.User EndAuthenticate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainServerFunctions/RegisterUser", ReplyAction="http://tempuri.org/IMainServerFunctions/RegisterUserResponse")]
        bool RegisterUser(ComCon.Client.Base.ServerService.Credentials pCredentials);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMainServerFunctions/RegisterUser", ReplyAction="http://tempuri.org/IMainServerFunctions/RegisterUserResponse")]
        System.IAsyncResult BeginRegisterUser(ComCon.Client.Base.ServerService.Credentials pCredentials, System.AsyncCallback callback, object asyncState);
        
        bool EndRegisterUser(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainServerFunctionsChannel : ComCon.Client.Base.ServerService.IMainServerFunctions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComCon.Client.Base.ServerService.User Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComCon.Client.Base.ServerService.User)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegisterUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainServerFunctionsClient : System.ServiceModel.ClientBase<ComCon.Client.Base.ServerService.IMainServerFunctions>, ComCon.Client.Base.ServerService.IMainServerFunctions {
        
        private BeginOperationDelegate onBeginAuthenticateDelegate;
        
        private EndOperationDelegate onEndAuthenticateDelegate;
        
        private System.Threading.SendOrPostCallback onAuthenticateCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegisterUserDelegate;
        
        private EndOperationDelegate onEndRegisterUserDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterUserCompletedDelegate;
        
        public MainServerFunctionsClient() {
        }
        
        public MainServerFunctionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainServerFunctionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServerFunctionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServerFunctionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AuthenticateCompletedEventArgs> AuthenticateCompleted;
        
        public event System.EventHandler<RegisterUserCompletedEventArgs> RegisterUserCompleted;
        
        public ComCon.Client.Base.ServerService.User Authenticate(ComCon.Client.Base.ServerService.Credentials pCredentials) {
            return base.Channel.Authenticate(pCredentials);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAuthenticate(ComCon.Client.Base.ServerService.Credentials pCredentials, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthenticate(pCredentials, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ComCon.Client.Base.ServerService.User EndAuthenticate(System.IAsyncResult result) {
            return base.Channel.EndAuthenticate(result);
        }
        
        private System.IAsyncResult OnBeginAuthenticate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComCon.Client.Base.ServerService.Credentials pCredentials = ((ComCon.Client.Base.ServerService.Credentials)(inValues[0]));
            return this.BeginAuthenticate(pCredentials, callback, asyncState);
        }
        
        private object[] OnEndAuthenticate(System.IAsyncResult result) {
            ComCon.Client.Base.ServerService.User retVal = this.EndAuthenticate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthenticateCompleted(object state) {
            if ((this.AuthenticateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthenticateAsync(ComCon.Client.Base.ServerService.Credentials pCredentials) {
            this.AuthenticateAsync(pCredentials, null);
        }
        
        public void AuthenticateAsync(ComCon.Client.Base.ServerService.Credentials pCredentials, object userState) {
            if ((this.onBeginAuthenticateDelegate == null)) {
                this.onBeginAuthenticateDelegate = new BeginOperationDelegate(this.OnBeginAuthenticate);
            }
            if ((this.onEndAuthenticateDelegate == null)) {
                this.onEndAuthenticateDelegate = new EndOperationDelegate(this.OnEndAuthenticate);
            }
            if ((this.onAuthenticateCompletedDelegate == null)) {
                this.onAuthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateDelegate, new object[] {
                        pCredentials}, this.onEndAuthenticateDelegate, this.onAuthenticateCompletedDelegate, userState);
        }
        
        public bool RegisterUser(ComCon.Client.Base.ServerService.Credentials pCredentials) {
            return base.Channel.RegisterUser(pCredentials);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRegisterUser(ComCon.Client.Base.ServerService.Credentials pCredentials, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegisterUser(pCredentials, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndRegisterUser(System.IAsyncResult result) {
            return base.Channel.EndRegisterUser(result);
        }
        
        private System.IAsyncResult OnBeginRegisterUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComCon.Client.Base.ServerService.Credentials pCredentials = ((ComCon.Client.Base.ServerService.Credentials)(inValues[0]));
            return this.BeginRegisterUser(pCredentials, callback, asyncState);
        }
        
        private object[] OnEndRegisterUser(System.IAsyncResult result) {
            bool retVal = this.EndRegisterUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegisterUserCompleted(object state) {
            if ((this.RegisterUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterUserCompleted(this, new RegisterUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterUserAsync(ComCon.Client.Base.ServerService.Credentials pCredentials) {
            this.RegisterUserAsync(pCredentials, null);
        }
        
        public void RegisterUserAsync(ComCon.Client.Base.ServerService.Credentials pCredentials, object userState) {
            if ((this.onBeginRegisterUserDelegate == null)) {
                this.onBeginRegisterUserDelegate = new BeginOperationDelegate(this.OnBeginRegisterUser);
            }
            if ((this.onEndRegisterUserDelegate == null)) {
                this.onEndRegisterUserDelegate = new EndOperationDelegate(this.OnEndRegisterUser);
            }
            if ((this.onRegisterUserCompletedDelegate == null)) {
                this.onRegisterUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterUserCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterUserDelegate, new object[] {
                        pCredentials}, this.onEndRegisterUserDelegate, this.onRegisterUserCompletedDelegate, userState);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerService.IChatServerFunctions", CallbackContract=typeof(ComCon.Client.Base.ServerService.IChatServerFunctionsCallback))]
    public interface IChatServerFunctions {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServerFunctions/ConnectToServer", ReplyAction="http://tempuri.org/IChatServerFunctions/ConnectToServerResponse")]
        ComCon.Client.Base.ServerService.User ConnectToServer(ComCon.Client.Base.ServerService.Credentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IChatServerFunctions/ConnectToServer", ReplyAction="http://tempuri.org/IChatServerFunctions/ConnectToServerResponse")]
        System.IAsyncResult BeginConnectToServer(ComCon.Client.Base.ServerService.Credentials credentials, System.AsyncCallback callback, object asyncState);
        
        ComCon.Client.Base.ServerService.User EndConnectToServer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServerFunctions/DisconnectFromServer", ReplyAction="http://tempuri.org/IChatServerFunctions/DisconnectFromServerResponse")]
        void DisconnectFromServer();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IChatServerFunctions/DisconnectFromServer", ReplyAction="http://tempuri.org/IChatServerFunctions/DisconnectFromServerResponse")]
        System.IAsyncResult BeginDisconnectFromServer(System.AsyncCallback callback, object asyncState);
        
        void EndDisconnectFromServer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServerFunctions/Send", ReplyAction="http://tempuri.org/IChatServerFunctions/SendResponse")]
        void Send(ComCon.Client.Base.ServerService.ChatMessage cm);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IChatServerFunctions/Send", ReplyAction="http://tempuri.org/IChatServerFunctions/SendResponse")]
        System.IAsyncResult BeginSend(ComCon.Client.Base.ServerService.ChatMessage cm, System.AsyncCallback callback, object asyncState);
        
        void EndSend(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServerFunctions/ConnectToChannel", ReplyAction="http://tempuri.org/IChatServerFunctions/ConnectToChannelResponse")]
        void ConnectToChannel();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IChatServerFunctions/ConnectToChannel", ReplyAction="http://tempuri.org/IChatServerFunctions/ConnectToChannelResponse")]
        System.IAsyncResult BeginConnectToChannel(System.AsyncCallback callback, object asyncState);
        
        void EndConnectToChannel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServerFunctions/DisconnectFromChannel", ReplyAction="http://tempuri.org/IChatServerFunctions/DisconnectFromChannelResponse")]
        void DisconnectFromChannel();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IChatServerFunctions/DisconnectFromChannel", ReplyAction="http://tempuri.org/IChatServerFunctions/DisconnectFromChannelResponse")]
        System.IAsyncResult BeginDisconnectFromChannel(System.AsyncCallback callback, object asyncState);
        
        void EndDisconnectFromChannel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServerFunctions/GetChannels", ReplyAction="http://tempuri.org/IChatServerFunctions/GetChannelsResponse")]
        string[] GetChannels();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IChatServerFunctions/GetChannels", ReplyAction="http://tempuri.org/IChatServerFunctions/GetChannelsResponse")]
        System.IAsyncResult BeginGetChannels(System.AsyncCallback callback, object asyncState);
        
        string[] EndGetChannels(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServerFunctions/GetUser", ReplyAction="http://tempuri.org/IChatServerFunctions/GetUserResponse")]
        ComCon.Client.Base.ServerService.User GetUser(string pMail);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IChatServerFunctions/GetUser", ReplyAction="http://tempuri.org/IChatServerFunctions/GetUserResponse")]
        System.IAsyncResult BeginGetUser(string pMail, System.AsyncCallback callback, object asyncState);
        
        ComCon.Client.Base.ServerService.User EndGetUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServerFunctions/get_LoggedInUsers", ReplyAction="http://tempuri.org/IChatServerFunctions/get_LoggedInUsersResponse")]
        ComCon.Client.Base.ServerService.User[] get_LoggedInUsers();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IChatServerFunctions/get_LoggedInUsers", ReplyAction="http://tempuri.org/IChatServerFunctions/get_LoggedInUsersResponse")]
        System.IAsyncResult Beginget_LoggedInUsers(System.AsyncCallback callback, object asyncState);
        
        ComCon.Client.Base.ServerService.User[] Endget_LoggedInUsers(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServerFunctionsCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatServerFunctions/ShowMessage")]
        void ShowMessage(ComCon.Client.Base.ServerService.ChatMessage cm);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/IChatServerFunctions/ShowMessage")]
        System.IAsyncResult BeginShowMessage(ComCon.Client.Base.ServerService.ChatMessage cm, System.AsyncCallback callback, object asyncState);
        
        void EndShowMessage(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServerFunctionsChannel : ComCon.Client.Base.ServerService.IChatServerFunctions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConnectToServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConnectToServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComCon.Client.Base.ServerService.User Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComCon.Client.Base.ServerService.User)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetChannelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetChannelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComCon.Client.Base.ServerService.User Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComCon.Client.Base.ServerService.User)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class get_LoggedInUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public get_LoggedInUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ComCon.Client.Base.ServerService.User[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ComCon.Client.Base.ServerService.User[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServerFunctionsClient : System.ServiceModel.DuplexClientBase<ComCon.Client.Base.ServerService.IChatServerFunctions>, ComCon.Client.Base.ServerService.IChatServerFunctions {
        
        private BeginOperationDelegate onBeginConnectToServerDelegate;
        
        private EndOperationDelegate onEndConnectToServerDelegate;
        
        private System.Threading.SendOrPostCallback onConnectToServerCompletedDelegate;
        
        private BeginOperationDelegate onBeginDisconnectFromServerDelegate;
        
        private EndOperationDelegate onEndDisconnectFromServerDelegate;
        
        private System.Threading.SendOrPostCallback onDisconnectFromServerCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendDelegate;
        
        private EndOperationDelegate onEndSendDelegate;
        
        private System.Threading.SendOrPostCallback onSendCompletedDelegate;
        
        private BeginOperationDelegate onBeginConnectToChannelDelegate;
        
        private EndOperationDelegate onEndConnectToChannelDelegate;
        
        private System.Threading.SendOrPostCallback onConnectToChannelCompletedDelegate;
        
        private BeginOperationDelegate onBeginDisconnectFromChannelDelegate;
        
        private EndOperationDelegate onEndDisconnectFromChannelDelegate;
        
        private System.Threading.SendOrPostCallback onDisconnectFromChannelCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetChannelsDelegate;
        
        private EndOperationDelegate onEndGetChannelsDelegate;
        
        private System.Threading.SendOrPostCallback onGetChannelsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserDelegate;
        
        private EndOperationDelegate onEndGetUserDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginget_LoggedInUsersDelegate;
        
        private EndOperationDelegate onEndget_LoggedInUsersDelegate;
        
        private System.Threading.SendOrPostCallback onget_LoggedInUsersCompletedDelegate;
        
        public ChatServerFunctionsClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatServerFunctionsClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatServerFunctionsClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServerFunctionsClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServerFunctionsClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public event System.EventHandler<ConnectToServerCompletedEventArgs> ConnectToServerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DisconnectFromServerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SendCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ConnectToChannelCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DisconnectFromChannelCompleted;
        
        public event System.EventHandler<GetChannelsCompletedEventArgs> GetChannelsCompleted;
        
        public event System.EventHandler<GetUserCompletedEventArgs> GetUserCompleted;
        
        public event System.EventHandler<get_LoggedInUsersCompletedEventArgs> get_LoggedInUsersCompleted;
        
        public ComCon.Client.Base.ServerService.User ConnectToServer(ComCon.Client.Base.ServerService.Credentials credentials) {
            return base.Channel.ConnectToServer(credentials);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConnectToServer(ComCon.Client.Base.ServerService.Credentials credentials, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConnectToServer(credentials, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ComCon.Client.Base.ServerService.User EndConnectToServer(System.IAsyncResult result) {
            return base.Channel.EndConnectToServer(result);
        }
        
        private System.IAsyncResult OnBeginConnectToServer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComCon.Client.Base.ServerService.Credentials credentials = ((ComCon.Client.Base.ServerService.Credentials)(inValues[0]));
            return this.BeginConnectToServer(credentials, callback, asyncState);
        }
        
        private object[] OnEndConnectToServer(System.IAsyncResult result) {
            ComCon.Client.Base.ServerService.User retVal = this.EndConnectToServer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConnectToServerCompleted(object state) {
            if ((this.ConnectToServerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConnectToServerCompleted(this, new ConnectToServerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConnectToServerAsync(ComCon.Client.Base.ServerService.Credentials credentials) {
            this.ConnectToServerAsync(credentials, null);
        }
        
        public void ConnectToServerAsync(ComCon.Client.Base.ServerService.Credentials credentials, object userState) {
            if ((this.onBeginConnectToServerDelegate == null)) {
                this.onBeginConnectToServerDelegate = new BeginOperationDelegate(this.OnBeginConnectToServer);
            }
            if ((this.onEndConnectToServerDelegate == null)) {
                this.onEndConnectToServerDelegate = new EndOperationDelegate(this.OnEndConnectToServer);
            }
            if ((this.onConnectToServerCompletedDelegate == null)) {
                this.onConnectToServerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConnectToServerCompleted);
            }
            base.InvokeAsync(this.onBeginConnectToServerDelegate, new object[] {
                        credentials}, this.onEndConnectToServerDelegate, this.onConnectToServerCompletedDelegate, userState);
        }
        
        public void DisconnectFromServer() {
            base.Channel.DisconnectFromServer();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDisconnectFromServer(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDisconnectFromServer(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDisconnectFromServer(System.IAsyncResult result) {
            base.Channel.EndDisconnectFromServer(result);
        }
        
        private System.IAsyncResult OnBeginDisconnectFromServer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDisconnectFromServer(callback, asyncState);
        }
        
        private object[] OnEndDisconnectFromServer(System.IAsyncResult result) {
            this.EndDisconnectFromServer(result);
            return null;
        }
        
        private void OnDisconnectFromServerCompleted(object state) {
            if ((this.DisconnectFromServerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DisconnectFromServerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DisconnectFromServerAsync() {
            this.DisconnectFromServerAsync(null);
        }
        
        public void DisconnectFromServerAsync(object userState) {
            if ((this.onBeginDisconnectFromServerDelegate == null)) {
                this.onBeginDisconnectFromServerDelegate = new BeginOperationDelegate(this.OnBeginDisconnectFromServer);
            }
            if ((this.onEndDisconnectFromServerDelegate == null)) {
                this.onEndDisconnectFromServerDelegate = new EndOperationDelegate(this.OnEndDisconnectFromServer);
            }
            if ((this.onDisconnectFromServerCompletedDelegate == null)) {
                this.onDisconnectFromServerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDisconnectFromServerCompleted);
            }
            base.InvokeAsync(this.onBeginDisconnectFromServerDelegate, null, this.onEndDisconnectFromServerDelegate, this.onDisconnectFromServerCompletedDelegate, userState);
        }
        
        public void Send(ComCon.Client.Base.ServerService.ChatMessage cm) {
            base.Channel.Send(cm);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSend(ComCon.Client.Base.ServerService.ChatMessage cm, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSend(cm, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndSend(System.IAsyncResult result) {
            base.Channel.EndSend(result);
        }
        
        private System.IAsyncResult OnBeginSend(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ComCon.Client.Base.ServerService.ChatMessage cm = ((ComCon.Client.Base.ServerService.ChatMessage)(inValues[0]));
            return this.BeginSend(cm, callback, asyncState);
        }
        
        private object[] OnEndSend(System.IAsyncResult result) {
            this.EndSend(result);
            return null;
        }
        
        private void OnSendCompleted(object state) {
            if ((this.SendCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendAsync(ComCon.Client.Base.ServerService.ChatMessage cm) {
            this.SendAsync(cm, null);
        }
        
        public void SendAsync(ComCon.Client.Base.ServerService.ChatMessage cm, object userState) {
            if ((this.onBeginSendDelegate == null)) {
                this.onBeginSendDelegate = new BeginOperationDelegate(this.OnBeginSend);
            }
            if ((this.onEndSendDelegate == null)) {
                this.onEndSendDelegate = new EndOperationDelegate(this.OnEndSend);
            }
            if ((this.onSendCompletedDelegate == null)) {
                this.onSendCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendCompleted);
            }
            base.InvokeAsync(this.onBeginSendDelegate, new object[] {
                        cm}, this.onEndSendDelegate, this.onSendCompletedDelegate, userState);
        }
        
        public void ConnectToChannel() {
            base.Channel.ConnectToChannel();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConnectToChannel(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConnectToChannel(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndConnectToChannel(System.IAsyncResult result) {
            base.Channel.EndConnectToChannel(result);
        }
        
        private System.IAsyncResult OnBeginConnectToChannel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginConnectToChannel(callback, asyncState);
        }
        
        private object[] OnEndConnectToChannel(System.IAsyncResult result) {
            this.EndConnectToChannel(result);
            return null;
        }
        
        private void OnConnectToChannelCompleted(object state) {
            if ((this.ConnectToChannelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConnectToChannelCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConnectToChannelAsync() {
            this.ConnectToChannelAsync(null);
        }
        
        public void ConnectToChannelAsync(object userState) {
            if ((this.onBeginConnectToChannelDelegate == null)) {
                this.onBeginConnectToChannelDelegate = new BeginOperationDelegate(this.OnBeginConnectToChannel);
            }
            if ((this.onEndConnectToChannelDelegate == null)) {
                this.onEndConnectToChannelDelegate = new EndOperationDelegate(this.OnEndConnectToChannel);
            }
            if ((this.onConnectToChannelCompletedDelegate == null)) {
                this.onConnectToChannelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConnectToChannelCompleted);
            }
            base.InvokeAsync(this.onBeginConnectToChannelDelegate, null, this.onEndConnectToChannelDelegate, this.onConnectToChannelCompletedDelegate, userState);
        }
        
        public void DisconnectFromChannel() {
            base.Channel.DisconnectFromChannel();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDisconnectFromChannel(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDisconnectFromChannel(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDisconnectFromChannel(System.IAsyncResult result) {
            base.Channel.EndDisconnectFromChannel(result);
        }
        
        private System.IAsyncResult OnBeginDisconnectFromChannel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDisconnectFromChannel(callback, asyncState);
        }
        
        private object[] OnEndDisconnectFromChannel(System.IAsyncResult result) {
            this.EndDisconnectFromChannel(result);
            return null;
        }
        
        private void OnDisconnectFromChannelCompleted(object state) {
            if ((this.DisconnectFromChannelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DisconnectFromChannelCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DisconnectFromChannelAsync() {
            this.DisconnectFromChannelAsync(null);
        }
        
        public void DisconnectFromChannelAsync(object userState) {
            if ((this.onBeginDisconnectFromChannelDelegate == null)) {
                this.onBeginDisconnectFromChannelDelegate = new BeginOperationDelegate(this.OnBeginDisconnectFromChannel);
            }
            if ((this.onEndDisconnectFromChannelDelegate == null)) {
                this.onEndDisconnectFromChannelDelegate = new EndOperationDelegate(this.OnEndDisconnectFromChannel);
            }
            if ((this.onDisconnectFromChannelCompletedDelegate == null)) {
                this.onDisconnectFromChannelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDisconnectFromChannelCompleted);
            }
            base.InvokeAsync(this.onBeginDisconnectFromChannelDelegate, null, this.onEndDisconnectFromChannelDelegate, this.onDisconnectFromChannelCompletedDelegate, userState);
        }
        
        public string[] GetChannels() {
            return base.Channel.GetChannels();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetChannels(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetChannels(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string[] EndGetChannels(System.IAsyncResult result) {
            return base.Channel.EndGetChannels(result);
        }
        
        private System.IAsyncResult OnBeginGetChannels(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetChannels(callback, asyncState);
        }
        
        private object[] OnEndGetChannels(System.IAsyncResult result) {
            string[] retVal = this.EndGetChannels(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetChannelsCompleted(object state) {
            if ((this.GetChannelsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetChannelsCompleted(this, new GetChannelsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetChannelsAsync() {
            this.GetChannelsAsync(null);
        }
        
        public void GetChannelsAsync(object userState) {
            if ((this.onBeginGetChannelsDelegate == null)) {
                this.onBeginGetChannelsDelegate = new BeginOperationDelegate(this.OnBeginGetChannels);
            }
            if ((this.onEndGetChannelsDelegate == null)) {
                this.onEndGetChannelsDelegate = new EndOperationDelegate(this.OnEndGetChannels);
            }
            if ((this.onGetChannelsCompletedDelegate == null)) {
                this.onGetChannelsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetChannelsCompleted);
            }
            base.InvokeAsync(this.onBeginGetChannelsDelegate, null, this.onEndGetChannelsDelegate, this.onGetChannelsCompletedDelegate, userState);
        }
        
        public ComCon.Client.Base.ServerService.User GetUser(string pMail) {
            return base.Channel.GetUser(pMail);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetUser(string pMail, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUser(pMail, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ComCon.Client.Base.ServerService.User EndGetUser(System.IAsyncResult result) {
            return base.Channel.EndGetUser(result);
        }
        
        private System.IAsyncResult OnBeginGetUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pMail = ((string)(inValues[0]));
            return this.BeginGetUser(pMail, callback, asyncState);
        }
        
        private object[] OnEndGetUser(System.IAsyncResult result) {
            ComCon.Client.Base.ServerService.User retVal = this.EndGetUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserCompleted(object state) {
            if ((this.GetUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserCompleted(this, new GetUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserAsync(string pMail) {
            this.GetUserAsync(pMail, null);
        }
        
        public void GetUserAsync(string pMail, object userState) {
            if ((this.onBeginGetUserDelegate == null)) {
                this.onBeginGetUserDelegate = new BeginOperationDelegate(this.OnBeginGetUser);
            }
            if ((this.onEndGetUserDelegate == null)) {
                this.onEndGetUserDelegate = new EndOperationDelegate(this.OnEndGetUser);
            }
            if ((this.onGetUserCompletedDelegate == null)) {
                this.onGetUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserDelegate, new object[] {
                        pMail}, this.onEndGetUserDelegate, this.onGetUserCompletedDelegate, userState);
        }
        
        public ComCon.Client.Base.ServerService.User[] get_LoggedInUsers() {
            return base.Channel.get_LoggedInUsers();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginget_LoggedInUsers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginget_LoggedInUsers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ComCon.Client.Base.ServerService.User[] Endget_LoggedInUsers(System.IAsyncResult result) {
            return base.Channel.Endget_LoggedInUsers(result);
        }
        
        private System.IAsyncResult OnBeginget_LoggedInUsers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.Beginget_LoggedInUsers(callback, asyncState);
        }
        
        private object[] OnEndget_LoggedInUsers(System.IAsyncResult result) {
            ComCon.Client.Base.ServerService.User[] retVal = this.Endget_LoggedInUsers(result);
            return new object[] {
                    retVal};
        }
        
        private void Onget_LoggedInUsersCompleted(object state) {
            if ((this.get_LoggedInUsersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.get_LoggedInUsersCompleted(this, new get_LoggedInUsersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void get_LoggedInUsersAsync() {
            this.get_LoggedInUsersAsync(null);
        }
        
        public void get_LoggedInUsersAsync(object userState) {
            if ((this.onBeginget_LoggedInUsersDelegate == null)) {
                this.onBeginget_LoggedInUsersDelegate = new BeginOperationDelegate(this.OnBeginget_LoggedInUsers);
            }
            if ((this.onEndget_LoggedInUsersDelegate == null)) {
                this.onEndget_LoggedInUsersDelegate = new EndOperationDelegate(this.OnEndget_LoggedInUsers);
            }
            if ((this.onget_LoggedInUsersCompletedDelegate == null)) {
                this.onget_LoggedInUsersCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onget_LoggedInUsersCompleted);
            }
            base.InvokeAsync(this.onBeginget_LoggedInUsersDelegate, null, this.onEndget_LoggedInUsersDelegate, this.onget_LoggedInUsersCompletedDelegate, userState);
        }
    }
}
